# sudo permisson is required for root access in order to execute this build 
sudo: required 

# Hey travis we need a copy of docker
services: 
  - docker

# this is used because we build docker image before the test run
before_install:
  - docker build -t ronak07/docker-react -f Dockerfile.dev .

# script is used to run our test suite
script:
  - docker run -e CI=true ronak07/docker-react npm run test 

# Tell Travis if test is complete how to deploy our app to aws..
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-273134686484"
  bucket_path: "docker"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY