# this file specifies it is only used for development purposes...
 
# create a base image of node image

FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]


